/* when there is no child class constructor present and parent class constructor is present 
and we call 
the child class constructor , it will automatically call the 
parent class constructor, compiler will auto generate the code 
*/

class Parent 
{
Parent()
{
System.out.println("parent class 0-arg cons");
}
}
class Child extends Parent
{

/*  code is generated by compiler
  Child()
{
super();
}   */   // 
public static void main(String []args)
{
new Child();  // there is no child class constructor still it able to call it because of compiler.
}
}